spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/crudCarritoCompras
    username: postgres
    password: Neicer1403-...
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/crudCarritoCompras
    user: postgres
    password: Neicer1403-...
    locations: classpath:db/migration
