spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/administracionesdb
    username: postgres
    password: 1q2w3e4r5t6y

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"